// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALq_o1Kqs0e14d2inUC7Oy3_ndxt6HKtQ',
    appId: '1:80843729525:web:20f0ef138e7651b77fe63c',
    messagingSenderId: '80843729525',
    projectId: 'nlcshub',
    authDomain: 'nlcshub.firebaseapp.com',
    storageBucket: 'nlcshub.appspot.com',
    measurementId: 'G-7LNWTQSGK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOazgs909eZZ-jnl2ZprDdg3wjakEJh4',
    appId: '1:80843729525:android:975cee2cfdb0d3487fe63c',
    messagingSenderId: '80843729525',
    projectId: 'nlcshub',
    storageBucket: 'nlcshub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVxtxP9LpHZcLvSi48EyK1PKk92XYf6fU',
    appId: '1:80843729525:ios:1f2ac9d51fe3a74f7fe63c',
    messagingSenderId: '80843729525',
    projectId: 'nlcshub',
    storageBucket: 'nlcshub.appspot.com',
    iosClientId:
        '80843729525-c1i0ap14o59394diiv3a7f22rb5km879.apps.googleusercontent.com',
    iosBundleId: 'com.nlcsjeju.nlcshubmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVxtxP9LpHZcLvSi48EyK1PKk92XYf6fU',
    appId: '1:80843729525:ios:1f2ac9d51fe3a74f7fe63c',
    messagingSenderId: '80843729525',
    projectId: 'nlcshub',
    storageBucket: 'nlcshub.appspot.com',
    iosClientId:
        '80843729525-c1i0ap14o59394diiv3a7f22rb5km879.apps.googleusercontent.com',
    iosBundleId: 'com.nlcsjeju.nlcshubmobile',
  );
}
