/// Flutter icons HouseLogo
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HouseLogo
///      fonts:
///       - asset: fonts/HouseLogo.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HouseLogo {
  HouseLogo._();

  static const _kFontFam = 'HouseLogo';
  static const String? _kFontPkg = null;

  static const IconData jeoji = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geomun = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sarah = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mulchat = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noro = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}